### ISSUE TITLE
upgrade to hg38

### ISSUE THREAD

**Issue by raylim** [jrflab/modules#156]
hg19 is a bit old

**Comment by inodb** [comment]
Wouldn't this break a ton of things?

**Comment by raylim** [comment]
yeah, probably

**Comment by raylim** [comment]
we could use it in some particular cases; where we don't have to call variants for example

**Comment by raylim** [comment]
I mean single nucleotide/indel variants

**Comment by hxrts** [comment]
Not sure if it's acceptable to publish sample sets using two different references unless they're very large cohorts. May be an issue for projects where we dip into old sample batches.

**Comment by raylim** [comment]
That's a good point

**Comment by RodrigoGM** [comment]
Grch38 has been out since December 2013, I'm sure that by now the annotation and all upcoming papers will be using this assembly.  This annotation has several gaps, and misassembly corrections that would be worth while having when aligning exomes and whole genomes.

The change doesn't need to be drastic, is it feasible to make the commitment that all new projects are worked on using Grch38 ?

**Comment by inodb** [comment]
I don't think it's feasible to switch soon, because of all the different steps in the pipeline that use hg19 atm. This is a rough plan for switching:
- [ ] Determine why switching between hg19 and Grch38 is worthwhile
- [ ] Document all key workflows in pipeline
- [ ] Identify what parts of those workflows use hg19
  - [ ] For annotation determine/document exactly what databases we are using and if they support Grch38

**Comment by raylim** [comment]
Provean doesn't support GRch38 for example.  We would have to lift over each query/result.
